### ISSUE TITLE
RBR750 - TFTP block rollover. Upload might fail!

### ISSUE THREAD

**Issue by Goldstino** [jclehner/nmrpflash#130]
Any idea what can I do it flash it successfully? Everything is okay but I get the above message and then the firmware is not flashed.
https://imgur.com/a/ebcIdbT

**Comment by jclehner** [comment]
Please try this version, and report back. Are you trying to downgrade the firmware? Or reinstalling the same version?

[nmrpflash-0.9.20-5-g7d3124f-win32.zip](https://github.com/jclehner/nmrpflash/files/12171855/nmrpflash-0.9.20-5-g7d3124f-win32.zip)

**Comment by Goldstino** [comment]
Thank you for taking the time to respond and providing an updated file. However, this one throws an error of Timeout while waiting for ACK(1) when uploading is in progress.

https://imgur.com/a/uiu31aq

The router is provided by the ISP and has an ISP firmware. I am trying to flash generic firmware and I have tried both revisions up and down but unfortunately cannot succeed for some reason. Possible to look at the error to see what could be the issue? I tried the original nmrpflash file and while it can upload the firmware, it gives an error that TFTP block rollover, the upload might fail. After I get reboot router message, I reboot and firmware is not changed.

**Comment by jclehner** [comment]
How about this one?

[nmrpflash-0.9.20-9-g35e2aa2-win32.zip](https://github.com/jclehner/nmrpflash/files/12180673/nmrpflash-0.9.20-9-g35e2aa2-win32.zip)

**Comment by Goldstino** [comment]
No joy, same error as before timeout whle waiting for ACK(1)

**Comment by jclehner** [comment]
Please try this instead. If it still doesn't work, try running it with `-t 500`. In both cases, use `-vv`.

[nmrpflash-0.9.20-11-g0eb8d70-win32.zip](https://github.com/jclehner/nmrpflash/files/12191782/nmrpflash-0.9.20-11-g0eb8d70-win32.zip)

**Comment by Goldstino** [comment]
Thank you. Flashed with the same error as the original file "TFTP block rollover. Upload might fail!" But it didnt have additional messages which I had on original flash like Waiting for TFTP_UL_REQ etc. Please see image below for the output.

https://imgur.com/a/bLp2C8U

**Comment by jclehner** [comment]
> I tried the original nmrpflash file and while it can upload the firmware, it gives an error that TFTP block rollover, the upload might fail.

This is just a warning, that the upload *might* fail. In your case, it doesn't!

> The router is provided by the ISP and has an ISP firmware. I am trying to flash generic firmware and I have tried both revisions up and down but unfortunately cannot succeed for some reason. Possible to look at the error to see what could be the issue?

Not really, unfortunately, because the router seems to accept the file. What's the version of the ISP's firmware? You might be able to patch the stock firmware to a version number higher than the ISP-firmware, using my [patchchk](https://github.com/jclehner/patchchk) tool.


> After I get reboot router message, I reboot and firmware is not changed.

**Comment by Goldstino** [comment]
Sorry, I forgot to add switches and now have done it. It appears the firmware upload is happening but the router keeps coming back with the ISP's firmware after rebooting. During the process, the red light keeps flashing. With these switches, I get one additional message of "Drained 1 packet(s) from rx buffer.

https://imgur.com/a/oBSFB7O

The router has ISP's firmware V4.6.5.29 and I am trying to flash higher version RBR750-V4.6.14.3_2.3.12-signed.chk
Please see the screenshots above.

**Comment by Goldstino** [comment]
> > The router is provided by the ISP and has an ISP firmware. I am trying to flash generic firmware and I have tried both revisions up and down but unfortunately cannot succeed for some reason. Possible to look at the error to see what could be the issue?
> 
> Not really, unfortunately, because the router seems to accept the file. What's the version of the ISP's firmware? You might be able to patch the stock firmware to a version number higher than the ISP-firmware, using my [patchchk](https://github.com/jclehner/patchchk) tool.

You think I shall try flashing generic firmware lower than the ISP's version?

**Comment by jclehner** [comment]
Do you happen to have an ISP firmware file for your device?

**Comment by Goldstino** [comment]
Nope. Any leads how could I export it for you? The router debug.htm page does not show the telnet option for some reason.

**Comment by jclehner** [comment]
Through reverse engineering, I've managed to get a download link to the firmware file:

https://http.fw.updates1.netgear.com/rbr750/rdqas/ww/RBR750-V4.6.5.29_0.0.33.chk

Your device uses a different "board id" (`U12H415T50_NETGEAR`, compared to `U12H415T00_NETGEAR` for the regular RBR750), which is why it rejected the other firmware file. I've attached a version of the unbranded firmware, with the board id changed to match your device. **Note that flashing this could brick your device**!

[RBR750-V4.6.14.3_2.3.12-U12H415T50_NETGEAR.zip](https://drive.google.com/file/d/1C1n7QuQRHSgnzGW63VaqpENROdOs_tQK/view?usp=sharing)

**Comment by Goldstino** [comment]
Thanks a lot. Will give it a try once I get a chance.

**Comment by Goldstino** [comment]
I was able to flash the firmware attached but now I cannot login to the router configuration. Previously I had configured the router to have 192.168.10.1 ip address and after flashing, it connected with 192.168.1.1 but now I cannot connect to it (Tried both ethernet and wifi). In both instances, it shows the correct Ooredoo name and can connect to the wifi but is unable to login to the router configuration.

Have tried via mobile, laptop and desktop, including orbilogin etc. It just throws an error that "This site can’t be reached"

I am hoping this may be due to local network issue so will try it at work tomorrow to see what happens. Will keep you posted.

**Comment by jclehner** [comment]
Have you tried a [factory reset](https://kb.netgear.com/31486/How-do-I-reset-my-Orbi-system-to-factory-default-settings) with the unbranded firmware installed?

Also note that there's nothing saying that the Ooredoo RBR750 and the unbranded one are 100% identical. Without access to a serial console, this would be hard to debug, and goes way beyond the scope of `nmrpflash`. In fact, I'll be closing this soon, as the original issue (which was not a bug in the first place) has been resolved.

**Comment by Goldstino** [comment]
Yes have tried restting but the problem still remains the same. It appears the file was flash and default configuration is assigned. However when I try to login 192.168.1.1, it doesnt give a response at all. Tried all method, tried connecting it to the existing netowkr, standalong, different PCs etc. I cannot seem to connect.

https://imgur.com/a/q9soJbO

Anything else I could do to make it work?
